use_frameworks!

target 'SelfTableViewManager_Example' do
  pod 'SelfTableViewManager', :path => '../'

  target 'SelfTableViewManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
