use_frameworks!

platform :ios, '9.3'

target 'SelfTableViewManager_Example' do
  pod 'SelfTableViewManager', :path => '../'

  target 'SelfTableViewManager_Tests' do
    inherit! :search_paths
  end
end
