version: 2

jobs:
  build-and-test:
    macos:
      xcode: "9.2.0"
    
    machine:
      xcode:
        version: 9.2
      enable: true

    steps:
      - checkout

      - run:
          name: Bundle install
          command: bundle install

      - run:
          name: Install CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            bundle exec pod install --project-directory=Example

      - run:
          name: Build and run tests
          command: fastlane test

      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

  deploy:
    macos:
      xcode: "9.2.0"

    machine:
      xcode:
        version: 9.2
      enable: true
      
    steps:
      - checkout

      - run:
          name: Bundle install
          command: bundle install

      - run: 
          name: Git clean
          command: git clean -dfx

      - run:
          name: Pull
          command: git pull --tags

      - run: 
          name: Git Config user.name
          command: git config --global user.name "Julio Fernandes Jr"

      - run:
          name: Git Config user.email
          command: git config --global user.email "julio.fernandes87@gmail.com"

      - run: 
          name: Tag and pod
          command: bundle exec fastlane tag_and_pod

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build-and-test
